import {
  CaseFile,
  DetectiveRank,
  EquipmentItem,
  Achievement,
  DetectiveProfile,
  RankInfo,
  Task,
  TaskDifficulty,
  TaskCategory,
  AttributeType,
} from './types';

export const DIFFICULTY_REWARDS: Record<
  TaskDifficulty,
  { xp: number; gold: number; attributeXp: number }
> = {
  E: { xp: 40, gold: 10, attributeXp: 8 },
  D: { xp: 60, gold: 15, attributeXp: 12 },
  C: { xp: 80, gold: 20, attributeXp: 15 },
  B: { xp: 120, gold: 35, attributeXp: 18 },
  A: { xp: 180, gold: 50, attributeXp: 25 },
  S: { xp: 240, gold: 70, attributeXp: 35 },
};

export const RANKS: RankInfo[] = [
  {
    rank: 'ROOKIE',
    minLevel: 1,
    title: 'Rookie Investigator',
    description: 'Freshly badged. Taking on fundamental casework quests and finding your footing.',
  },
  {
    rank: 'DETECTIVE',
    minLevel: 3,
    title: 'Junior Detective',
    description: 'Proven instinct. Authorized to access intermediate crime scene forensics.',
  },
  {
    rank: 'INVESTIGATOR',
    minLevel: 6,
    title: 'Lead Investigator',
    description: 'Sharp analytical eye. Capable of untangling complex criminal conspiracies.',
  },
  {
    rank: 'INSPECTOR',
    minLevel: 10,
    title: 'District Inspector',
    description: 'Authoritative deduction master with access to high-clearance case archives.',
  },
  {
    rank: 'SPECIALIST',
    minLevel: 15,
    title: 'Forensic Specialist',
    description: 'Renowned expert in cipher analysis, contradictions, and motive tracking.',
  },
  {
    rank: 'SENIOR INVESTIGATOR',
    minLevel: 20,
    title: 'Senior Investigator',
    description: 'Elite clearance. Trusted with syndicates, corporate conspiracies, and cold cases.',
  },
  {
    rank: 'CHIEF INVESTIGATOR',
    minLevel: 25,
    title: 'Chief of Investigation',
    description: 'Supreme investigative command across all metropolitan divisions.',
  },
  {
    rank: 'MASTER DETECTIVE',
    minLevel: 30,
    title: 'Master Detective',
    description: 'Living legend of the bureau. No secret remains hidden from your deduction.',
  },
];

export function calculateXpForLevel(level: number): number {
  return Math.round(100 * Math.pow(level, 1.35));
}

export function getRankForLevel(level: number): DetectiveRank {
  for (let i = RANKS.length - 1; i >= 0; i--) {
    if (level >= RANKS[i].minLevel) {
      return RANKS[i].rank;
    }
  }
  return 'ROOKIE';
}

export const INITIAL_EQUIPMENT: EquipmentItem[] = [
  {
    id: 'eq_magnifying_glass',
    name: 'Brass Magnifying Glass',
    category: 'OPTICS',
    description: 'High-precision optical lens. Reveals hidden markings, residue, and micro-clues.',
    costGold: 120,
    isUnlocked: true,
    isEquipped: true,
    iconName: 'Search',
    perkDescription: '+15% Perception attribute growth & reveals subtle scene details',
    attributeBonuses: { perception: 2 },
  },
  {
    id: 'eq_field_camera',
    name: 'Field Rangefinder Camera',
    category: 'DOCUMENTATION',
    description: 'Heavy vintage 35mm camera. Captures immutable physical evidence on film.',
    costGold: 250,
    isUnlocked: false,
    isEquipped: false,
    iconName: 'Camera',
    perkDescription: '+20 XP bonus upon discovering Evidence with Field Camera',
    attributeBonuses: { intelligence: 2, perception: 1 },
  },
  {
    id: 'eq_chronograph_watch',
    name: 'Chronograph Pocket Watch',
    category: 'TIMEKEEPING',
    description: 'Swiss mechanical stopwatch with precision tachymeter. Essential for timeline reconciliation.',
    costGold: 350,
    isUnlocked: false,
    isEquipped: false,
    iconName: 'Watch',
    perkDescription: '+20 XP bonus upon establishing Timeline Contradictions & +2 Discipline',
    attributeBonuses: { discipline: 2, resilience: 1 },
  },
  {
    id: 'eq_master_key',
    name: 'Master Skeleton Key Set',
    category: 'UTILITY',
    description: 'Forged brass lockpick set capable of opening private safes and sealed drawers.',
    costGold: 450,
    isUnlocked: false,
    isEquipped: false,
    iconName: 'Key',
    perkDescription: 'Reduces Gold cost of physical investigation actions by 15%',
    attributeBonuses: { intelligence: 2, perception: 1 },
  },
  {
    id: 'eq_trenchcoat',
    name: 'Inspector Wool Trenchcoat',
    category: 'APPAREL',
    description: 'Tailored heavy storm coat with deep interior dossier pockets and weathered lapels.',
    costGold: 600,
    isUnlocked: false,
    isEquipped: false,
    iconName: 'Shield',
    perkDescription: 'Increases casework Gold yield by +20% & boosts all attribute gains by 5%',
    attributeBonuses: { discipline: 2, resilience: 2 },
  },
  {
    id: 'eq_antique_typewriter',
    name: 'Antique Remington Typewriter',
    category: 'COLLECTIBLE',
    description: 'Cast-iron mechanical typewriter. Types official case closure reports with supreme authority.',
    costGold: 800,
    isUnlocked: false,
    isEquipped: false,
    iconName: 'FileText',
    perkDescription: '+50% Gold bonus upon canonical case solution & prestigious HQ badge',
    attributeBonuses: { intelligence: 3, resilience: 2 },
  },
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach_first_task',
    code: 'FIRST_OBJECTIVE',
    title: 'First Assignment',
    description: 'Complete your first real-world task docket and earn initial XP and Gold.',
    category: 'PRODUCTIVITY',
    icon: 'CheckCircle',
    rewardXp: 50,
    rewardGold: 30,
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_first_case',
    code: 'FIRST_CASE',
    title: 'First Case',
    description: 'Open and initiate your first active investigation docket.',
    category: 'INVESTIGATION',
    icon: 'Briefcase',
    rewardXp: 75,
    rewardGold: 50,
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_sharp_eyes',
    code: 'SHARP_EYES',
    title: 'Sharp Eyes',
    description: 'Discover 5 distinct pieces of evidence across crime scenes.',
    category: 'INVESTIGATION',
    icon: 'Eye',
    rewardXp: 120,
    rewardGold: 75,
    isUnlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'ach_cold_case',
    code: 'COLD_CASE',
    title: 'Investigation Streak',
    description: 'Maintain a 3-day consecutive task completion streak.',
    category: 'PRODUCTIVITY',
    icon: 'Flame',
    rewardXp: 200,
    rewardGold: 100,
    isUnlocked: false,
    progress: 1,
    maxProgress: 3,
  },
  {
    id: 'ach_red_yarn',
    code: 'RED_THREAD',
    title: 'Thread of Truth',
    description: 'Connect two correlating or contradictory evidence nodes on the Evidence Board.',
    category: 'DEDUCTION',
    icon: 'Share2',
    rewardXp: 100,
    rewardGold: 60,
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_master_deduction',
    code: 'MASTER_DEDUCTION',
    title: 'Master of Details',
    description: 'Successfully form 3 valid evidence deductions without false theories.',
    category: 'DEDUCTION',
    icon: 'Brain',
    rewardXp: 250,
    rewardGold: 150,
    isUnlocked: false,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'ach_case_closed',
    code: 'CASE_CLOSED',
    title: 'Case #001 Closed',
    description: 'Solve the canonical murder of Case #001: The Blackwood Murder.',
    category: 'MASTERY',
    icon: 'Award',
    rewardXp: 500,
    rewardGold: 250,
    isUnlocked: false,
    progress: 0,
    maxProgress: 1,
  },
  {
    id: 'ach_polymath',
    code: 'POLYMATH',
    title: 'Polymath Mind',
    description: 'Raise all 4 detective attributes to Level 5 or higher.',
    category: 'MASTERY',
    icon: 'Cpu',
    rewardXp: 300,
    rewardGold: 200,
    isUnlocked: false,
    progress: 0,
    maxProgress: 4,
  },
];

// ==========================================================
// CASE #001: THE BLACKWOOD MURDER (STARTS UNSOLVED)
// ==========================================================
export const INITIAL_CASES: CaseFile[] = [
  {
    id: 'case_001',
    code: 'CASE #001',
    title: 'THE BLACKWOOD MURDER',
    subtitle: 'Death in the Sealed Study',
    synopsis:
      'Lord Arthur Blackwood, patriarch of Blackwood Maritime & Ironworks, was found dead over his mahogany desk at 22:45 PM. The study door was locked from the inside, the vintage wall safe was left slightly ajar with scratch marks on the dial, a message was deleted from his laptop at 22:47, and a half-written codicil lay beside an overturned crystal glass.',
    location: 'Blackwood Manor, North Cliff',
    status: 'IN_PROGRESS',
    currentChapterId: 'ch_01',
    reqRank: 'ROOKIE',
    rewardXp: 500,
    rewardGold: 250,
    rewardBadge: 'Blackwood Case Master Seal',
    chapters: [
      {
        id: 'ch_01',
        caseId: 'case_001',
        chapterNumber: 1,
        title: 'The Sealed Study & Laptop',
        objective: 'Examine the desk, recover the deleted digital message, and inspect the safe dial.',
        isUnlocked: true,
        isCompleted: false,
        requiredEvidenceCount: 3,
      },
      {
        id: 'ch_02',
        caseId: 'case_001',
        chapterNumber: 2,
        title: 'The Garden & The Broken Watch',
        objective: 'Search the garden perimeter, recover the broken watch, and cross-reference gatehouse logs.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 5,
      },
      {
        id: 'ch_03',
        caseId: 'case_001',
        chapterNumber: 3,
        title: 'Interrogations & Alibi Contradictions',
        objective: 'Interrogate Marcus and Dr. Elena regarding potassium cyanide access and carriage departure times.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 8,
      },
      {
        id: 'ch_04',
        caseId: 'case_001',
        chapterNumber: 4,
        title: 'The Final Deduction',
        objective: 'Formulate the canonical deduction: Who, When, How, and Why.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 8,
      },
    ],
    suspects: [
      {
        id: 'susp_marcus',
        name: 'Marcus Vance',
        role: 'Nephew & Primary Estate Executor',
        alibi: 'Claims he kissed Arthur goodnight and departed the manor gate at 22:00 PM sharp in his carriage.',
        motiveSummary: 'Drowning in gambling debt to dockside bookmakers; learned Arthur planned to disinherit him tonight in favor of Clara.',
        avatarUrl: '/avatars/marcus.png',
        statusNotes: 'Nervously adjusting cufflinks during interrogation; pocket watch missing its gold bezel.',
      },
      {
        id: 'susp_elena',
        name: 'Dr. Elena Sterling',
        role: 'Personal Physician & Toxicologist',
        alibi: 'States she was in the downstairs parlor preparing Lord Blackwood’s daily heart tonic until 22:30 PM.',
        motiveSummary: 'Arthur threatened to report her unauthorized laboratory clinical trials to the Metropolitan Medical Board.',
        avatarUrl: '/avatars/elena.png',
        statusNotes: 'Composed demeanor; dispensary register shows checked out potassium cyanide for pest control.',
      },
      {
        id: 'susp_victor',
        name: 'Victor Ward',
        role: 'Business Partner & Ironworks Director',
        alibi: 'In the East Library reviewing quarterly shipping ledgers from 21:30 PM until the alarm was raised.',
        motiveSummary: 'Disputed Blackwood shipping patent rights and impending corporate buyout contract.',
        avatarUrl: '/avatars/victor.png',
        statusNotes: 'Provided audited company books willingly; claims he saw Marcus pacing near the garden shed at 22:15.',
      },
      {
        id: 'susp_clara',
        name: 'Clara Giles',
        role: 'Estate Archivist & Secret Heiress',
        alibi: 'Categorizing antique deeds in the archival vault until hearing the butler’s shout at 22:45 PM.',
        motiveSummary: 'Recently discovered Arthur was her biological father who kept her identity secret for 22 years.',
        avatarUrl: '/avatars/clara.png',
        statusNotes: 'Grief-stricken but clear; found the torn codicil amendment in the study wastepaper basket.',
      },
    ],
    evidence: [
      {
        id: 'ev_01',
        caseId: 'case_001',
        chapterId: 'ch_01',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 80, y: 120 },
      },
      {
        id: 'ev_02',
        caseId: 'case_001',
        chapterId: 'ch_01',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 340, y: 110 },
      },
      {
        id: 'ev_03',
        caseId: 'case_001',
        chapterId: 'ch_01',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 600, y: 120 },
      },
      {
        id: 'ev_04',
        caseId: 'case_001',
        chapterId: 'ch_01',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 860, y: 110 },
      },
      {
        id: 'ev_05',
        caseId: 'case_001',
        chapterId: 'ch_02',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 140, y: 340 },
      },
      {
        id: 'ev_06',
        caseId: 'case_001',
        chapterId: 'ch_02',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 420, y: 350 },
      },
      {
        id: 'ev_07',
        caseId: 'case_001',
        chapterId: 'ch_03',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 700, y: 340 },
      },
      {
        id: 'ev_08',
        caseId: 'case_001',
        chapterId: 'ch_03',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 300, y: 540 },
      },
      {
        id: 'ev_09',
        caseId: 'case_001',
        chapterId: 'ch_03',
        isDiscovered: false,
        pinnedOnBoard: false,
        boardPosition: { x: 620, y: 540 },
      },
    ],
    actions: [
      {
        id: 'act_01',
        caseId: 'case_001',
        sceneObjectId: 'obj_desk',
        sceneObjectName: 'Victim Mahogany Desk',
        title: 'SEARCH THE STUDY',
        description: 'Conduct forensic swab of the crystal tumbler and examine ink stains on the desk blotter.',
        costGold: 60,
        reqAttributes: { perception: 3 },
        potentialEvidenceLabel: 'Physical Evidence & Toxicology',
        yieldsEvidenceId: 'ev_01',
        findingsReport: 'Recovered crystal tumbler with trace potassium cyanide clinging to the crystal rim.',
        isExecuted: false,
        locationLabel: 'Study Desk Area',
      },
      {
        id: 'act_08',
        caseId: 'case_001',
        sceneObjectId: 'obj_wastebasket',
        sceneObjectName: 'Study Wastebasket',
        title: 'EXAMINE WASTEBASKET',
        description: 'Inspect the study wastebasket for discarded drafts and torn legal correspondence.',
        costGold: 40,
        reqAttributes: { perception: 2 },
        potentialEvidenceLabel: 'Torn Legal Document',
        yieldsEvidenceId: 'ev_02',
        findingsReport: 'Pieced together Arthur\'s handwritten draft disinheriting Marcus in favor of Clara Giles.',
        isExecuted: false,
        locationLabel: 'Study Corner',
      },
      {
        id: 'act_03',
        caseId: 'case_001',
        sceneObjectId: 'obj_safe',
        sceneObjectName: 'Wall Safe Behind Painting',
        title: 'EXAMINE WALL SAFE',
        description: 'Inspect dial gouge marks and catalog missing bearer bond serials.',
        costGold: 50,
        reqAttributes: { perception: 3 },
        potentialEvidenceLabel: 'Theft Evidence',
        yieldsEvidenceId: 'ev_03',
        findingsReport: 'Found fresh crowbar gouge marks matching forced entry on numbers 4-19-88.',
        isExecuted: false,
        locationLabel: 'North Wall Safe',
      },
      {
        id: 'act_02',
        caseId: 'case_001',
        sceneObjectId: 'obj_laptop',
        sceneObjectName: 'Arthur\'s Laptop Terminal',
        title: 'ANALYZE LAPTOP',
        description: 'Recover deleted file sectors and incoming telegraph cables from the secure disk.',
        costGold: 80,
        reqAttributes: { intelligence: 3 },
        alternateRoute: {
          reqAttributes: { discipline: 3 },
          label: 'Interrogate System Administrator',
        },
        potentialEvidenceLabel: 'Digital Evidence #07',
        yieldsEvidenceId: 'ev_04',
        findingsReport: 'Restored deleted message #07 sent at 22:47 regarding urgent gambling debt.',
        isExecuted: false,
        locationLabel: 'Digital Workstation',
      },
      {
        id: 'act_04',
        caseId: 'case_001',
        sceneObjectId: 'obj_garden',
        sceneObjectName: 'Garden Shed & Flowerbed',
        title: 'SEARCH THE GARDEN',
        description: 'Use flashlight and magnifying lens to search the muddy garden escape route.',
        costGold: 50,
        reqAttributes: { perception: 4 },
        potentialEvidenceLabel: 'Physical Broken Watch',
        yieldsEvidenceId: 'ev_05',
        findingsReport: 'Discovered Marcus Vance\'s crushed gold pocket watch stopped at 22:24 PM.',
        isExecuted: false,
        locationLabel: 'Garden Perimeter',
      },
      {
        id: 'act_05',
        caseId: 'case_001',
        sceneObjectId: 'obj_gate',
        sceneObjectName: 'Gatekeeper Register Log',
        title: 'RECONSTRUCT TIMELINE',
        description: 'Cross-examine gatekeeper records against suspect testimony timelines.',
        costGold: 90,
        reqAttributes: { discipline: 3 },
        alternateRoute: {
          reqAttributes: { intelligence: 3 },
          label: 'Analyze Timestamp Metadata',
        },
        potentialEvidenceLabel: 'Timeline Contradiction',
        yieldsEvidenceId: 'ev_06',
        findingsReport: 'Gatekeeper log confirms Marcus left at 22:31 PM, directly conflicting his 22:00 PM alibi.',
        isExecuted: false,
        locationLabel: 'Gatehouse Archive',
      },
      {
        id: 'act_06',
        caseId: 'case_001',
        sceneObjectId: 'obj_marcus_interrogate',
        sceneObjectName: 'Interrogation Suite',
        title: 'INTERVIEW MARCUS VANCE',
        description: 'Subject Marcus to aggressive timeline cross-examination regarding his carriage departure.',
        costGold: 70,
        reqAttributes: { discipline: 4 },
        potentialEvidenceLabel: 'Sworn Alibi Testimony',
        yieldsEvidenceId: 'ev_07',
        findingsReport: 'Marcus doubles down on his 22:00 departure alibi, cementing the contradiction with gate logs.',
        isExecuted: false,
        locationLabel: 'Interrogation Suite A',
      },
      {
        id: 'act_09',
        caseId: 'case_001',
        sceneObjectId: 'obj_physician_room',
        sceneObjectName: 'Physician\'s Quarters',
        title: 'INTERVIEW DR. ELENA STERLING',
        description: 'Question Dr. Elena regarding greenhouse pesticide registers and cyanide access logs.',
        costGold: 60,
        reqAttributes: { intelligence: 3 },
        alternateRoute: {
          reqAttributes: { perception: 3 },
          label: 'Search Medical Bag Discreetly',
        },
        potentialEvidenceLabel: 'Toxicology Dispensary Register',
        yieldsEvidenceId: 'ev_08',
        findingsReport: 'Recovered Dr. Elena\'s dispensary ledger showing 100mg potassium cyanide checked out for greenhouse pest control.',
        isExecuted: false,
        locationLabel: 'Doctor\'s Consulting Room',
      },
      {
        id: 'act_07',
        caseId: 'case_001',
        sceneObjectId: 'obj_library',
        sceneObjectName: 'East Library Wing',
        title: 'INSPECT LIBRARY & DESK PEN',
        description: 'Audit Lord Arthur\'s vintage writing desk and inspect his gold fountain pen.',
        costGold: 80,
        reqAttributes: { perception: 4 },
        potentialEvidenceLabel: 'Murder Weapon & Poison Source',
        yieldsEvidenceId: 'ev_09',
        findingsReport: 'Identified cyanide salt coating inside the fountain pen nib chewed by Arthur.',
        isExecuted: false,
        locationLabel: 'East Library Wing',
      },
    ],
    connections: [],
  },
  {
    id: 'case_002',
    code: 'CASE #002',
    title: 'THE SILENT WITNESS',
    subtitle: 'The Vault Breach at Zenith Gallery',
    synopsis:
      'High-security biometric vault compromised during an art gala without triggering infrared alarms. The master sapphire was swapped for a forged glass replica.',
    location: 'Zenith Gallery & High Vault',
    status: 'UNSOLVED',
    currentChapterId: 'ch_02_01',
    reqRank: 'INVESTIGATOR',
    rewardXp: 950,
    rewardGold: 500,
    rewardBadge: 'Silent Witness Seal',
    chapters: [
      {
        id: 'ch_02_01',
        caseId: 'case_002',
        chapterNumber: 1,
        title: 'The Vault Perimeter',
        objective: 'Analyze biometric override logs and inspect ceiling ventilation.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 3,
      },
    ],
    suspects: [],
    evidence: [],
    actions: [],
    connections: [],
  },
];

// ==========================================================
// STARTER QUESTS (FOR FRESH PRODUCTIVITY INVESTIGATION)
// ==========================================================
export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_01',
    title: 'COMPLETE DSA PRACTICE',
    description: 'Solve 2 algorithmic problems on graphs & dynamic programming to sharpen deduction logic.',
    category: 'Discipline',
    difficulty: 'B',
    priority: 'HIGH',
    xpReward: 120,
    goldReward: 35,
    attributeRewards: { discipline: 18, intelligence: 10 },
    isCompleted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_02',
    title: 'DEEP DIVE CODE AUDIT',
    description: 'Inspect 3 pull requests for subtle race conditions, memory leaks, and logic flaws.',
    category: 'Perception',
    difficulty: 'B',
    priority: 'HIGH',
    xpReward: 120,
    goldReward: 35,
    attributeRewards: { perception: 18, intelligence: 10 },
    isCompleted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_03',
    title: '30-MIN STAMINA CARDIO',
    description: 'High intensity physical conditioning to build resilience and mental fortitude.',
    category: 'Resilience',
    difficulty: 'C',
    priority: 'MEDIUM',
    xpReward: 80,
    goldReward: 20,
    attributeRewards: { resilience: 15, discipline: 10 },
    isCompleted: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_04',
    title: 'SYSTEM ARCHITECTURE DESIGN',
    description: 'Audit full-stack state machine flows and database transaction boundaries.',
    category: 'Intelligence',
    difficulty: 'A',
    priority: 'CRITICAL',
    xpReward: 180,
    goldReward: 50,
    attributeRewards: { intelligence: 25, resilience: 10 },
    isCompleted: false,
    createdAt: new Date().toISOString(),
  },
];

// ==========================================================
// INITIAL DETECTIVE PROFILE (STARTS AT LEVEL 1)
// ==========================================================
export const INITIAL_PROFILE: DetectiveProfile = {
  id: 'usr_detective_001',
  name: 'Alex Thorne',
  badgeId: 'BADGE #7429',
  email: 'thorne.detective@questchase.agency',
  rank: 'ROOKIE',
  level: 1,
  xp: 0,
  xpToNextLevel: 100,
  gold: 60,
  streak: 1,
  lastActiveDate: new Date().toISOString().split('T')[0],
  attributes: {
    intelligence: 3,
    perception: 3,
    discipline: 2,
    resilience: 2,
  },
  tasksCompletedCount: 0,
  casesSolvedCount: 0,
  evidenceDiscoveredCount: 0,
  equippedItems: ['eq_magnifying_glass'],
  settings: {
    audioEnabled: true,
    ambienceEnabled: true,
    reducedMotion: false,
  },
};
