// ==========================================================
// QUESTCHASE SERVER-ONLY CANONICAL CASE DEFINITIONS & EVIDENCE
// STRICTLY EXCLUDED FROM CLIENT BUNDLES & RESPONSES
// ==========================================================

import { CaseFile, EvidenceItem } from './types';

export const SERVER_CASES: CaseFile[] = [
  {
    id: 'case_001',
    code: 'CASE #001',
    title: 'THE BLACKWOOD MURDER',
    subtitle: 'The Cyanide in the Study',
    synopsis:
      'Lord Arthur Blackwood, patriarch of Blackwood Maritime & Ironworks, was found dead over his mahogany desk at 22:45. The study door was locked from the inside, the vintage wall safe was left slightly ajar with scratch marks on the dial, a message was deleted from his laptop at 22:47, and a half-written codicil lay beside an overturned crystal glass.',
    location: 'Blackwood Manor, North Cliff',
    status: 'IN_PROGRESS',
    currentChapterId: 'ch_01',
    reqRank: 'ROOKIE',
    rewardXp: 500,
    rewardGold: 250,
    rewardBadge: 'Blackwood Case Master Seal',
    chapters: [
      {
        id: 'ch_01',
        caseId: 'case_001',
        chapterNumber: 1,
        title: 'The Sealed Study & Laptop',
        objective: 'Examine the desk, recover the deleted digital message, and inspect the safe dial.',
        isUnlocked: true,
        isCompleted: false,
        requiredEvidenceCount: 3,
      },
      {
        id: 'ch_02',
        caseId: 'case_001',
        chapterNumber: 2,
        title: 'The Garden & The Broken Watch',
        objective: 'Search the garden perimeter, recover the broken watch, and cross-reference gatehouse logs.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 5,
      },
      {
        id: 'ch_03',
        caseId: 'case_001',
        chapterNumber: 3,
        title: 'Interrogations & Alibi Contradictions',
        objective: 'Interrogate Marcus and Dr. Elena regarding potassium cyanide access and carriage departure times.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 8,
      },
      {
        id: 'ch_04',
        caseId: 'case_001',
        chapterNumber: 4,
        title: 'The Final Deduction',
        objective: 'Formulate the canonical deduction: Who, When, How, and Why.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 8,
      },
    ],
    suspects: [
      {
        id: 'susp_marcus',
        name: 'Marcus Vance',
        role: 'Nephew & Primary Estate Executor',
        alibi: 'Claims he kissed Arthur goodnight and departed the manor gate at 22:00 sharp in his carriage.',
        motiveSummary: 'Drowning in gambling debt to dockside bookmakers; learned Arthur planned to disinherit him tonight in favor of Clara.',
        avatarUrl: '/avatars/marcus.png',
        statusNotes: 'Nervously adjusting cufflinks during interrogation; pocket watch missing its gold bezel.',
      },
      {
        id: 'susp_elena',
        name: 'Dr. Elena Sterling',
        role: 'Personal Physician & Toxicologist',
        alibi: 'States she was in the downstairs parlor preparing Lord Blackwood’s daily heart tonic until 22:30.',
        motiveSummary: 'Arthur threatened to report her unauthorized laboratory clinical trials to the Metropolitan Medical Board.',
        avatarUrl: '/avatars/elena.png',
        statusNotes: 'Composed demeanor; dispensary register shows checked out potassium cyanide for pest control.',
      },
      {
        id: 'susp_victor',
        name: 'Victor Ward',
        role: 'Business Partner & Ironworks Director',
        alibi: 'In the East Library reviewing quarterly shipping ledgers from 21:30 until the alarm was raised.',
        motiveSummary: 'Disputed Blackwood shipping patent rights and impending corporate buyout contract.',
        avatarUrl: '/avatars/victor.png',
        statusNotes: 'Provided audited company books willingly; claims he saw Marcus pacing near the garden shed at 22:15.',
      },
      {
        id: 'susp_clara',
        name: 'Clara Giles',
        role: 'Estate Archivist & Secret Heiress',
        alibi: 'Categorizing antique deeds in the archival vault until hearing the butler’s shout at 22:45.',
        motiveSummary: 'Recently discovered Arthur was her biological father who kept her identity secret for 22 years.',
        avatarUrl: '/avatars/clara.png',
        statusNotes: 'Grief-stricken but clear; found the torn codicil amendment in the study wastepaper basket.',
      },
    ],
    evidence: [
      {
        id: 'ev_01',
        caseId: 'case_001',
        chapterId: 'ch_01',
        title: 'Overturned Crystal Tumbler',
        type: 'PHYSICAL EVIDENCE',
        description: 'Single-malt scotch residue with distinct faint scent of bitter almonds clinging to the crystal rim.',
        detailedNotes: 'Forensic chemical reagent test confirms trace potassium cyanide mixed into high-proof scotch.',
        source: 'Victim Desk Surface',
        reliability: 'ABSOLUTE',
        connectedSuspects: ['Marcus Vance', 'Dr. Elena Sterling'],
        isDiscovered: false,
        tag: 'TOXICOLOGY',
        boardPosition: { x: 80, y: 120 },
      },
      {
        id: 'ev_02',
        caseId: 'case_001',
        chapterId: 'ch_01',
        title: 'Torn Codicil Draft',
        type: 'DOCUMENTS',
        description: 'Arthur’s handwritten amendment transferring 80% of ironworks shares to Clara Giles.',
        detailedNotes: 'Unsigned draft. The signature line ends in a violent fountain pen smear where the victim collapsed.',
        source: 'Study Wastebasket',
        reliability: 'HIGH',
        connectedSuspects: ['Marcus Vance', 'Clara Giles'],
        isDiscovered: false,
        tag: 'MOTIVE',
        boardPosition: { x: 340, y: 110 },
      },
      {
        id: 'ev_03',
        caseId: 'case_001',
        chapterId: 'ch_01',
        title: 'Scratch Marks on Wall Safe Dial',
        type: 'PHYSICAL EVIDENCE',
        description: 'Fresh metallic gouges near dial numbers 4 - 19 - 88. Safe door open 2 inches; bearer bonds missing.',
        detailedNotes: 'Indicates the thief lacked the true combination and forced the internal latch with a crowbar.',
        source: 'Behind Oil Portrait Wall Safe',
        reliability: 'HIGH',
        connectedSuspects: ['Marcus Vance'],
        isDiscovered: false,
        tag: 'THEFT',
        boardPosition: { x: 600, y: 120 },
      },
      {
        id: 'ev_04',
        caseId: 'case_001',
        chapterId: 'ch_01',
        title: 'Deleted Message #07',
        type: 'DIGITAL EVIDENCE',
        description: 'At 22:47, a message was deleted from the victim\'s laptop: "The debt cannot wait, Arthur."',
        detailedNotes: 'Recovered binary sectors confirm sender wire originated from dockside bookmaker linked to Marcus Vance.',
        source: 'Victim\'s Laptop',
        reliability: 'HIGH',
        connectedSuspects: ['Marcus Vance'],
        isDiscovered: false,
        tag: 'DIGITAL EVIDENCE',
        boardPosition: { x: 860, y: 110 },
      },
      {
        id: 'ev_05',
        caseId: 'case_001',
        chapterId: 'ch_02',
        title: 'Broken Gold Watch #14',
        type: 'PHYSICAL EVIDENCE',
        description: 'Antique gold pocket watch discovered crushed in the garden flowerbed. Hands stopped at 22:24.',
        detailedNotes: 'Engraved with initials "M.V.". Glass crystal shattered with traces of damp garden soil.',
        source: 'Garden Path Flowerbed',
        reliability: 'HIGH',
        connectedSuspects: ['Marcus Vance'],
        isDiscovered: false,
        tag: 'PHYSICAL EVIDENCE',
        boardPosition: { x: 140, y: 340 },
      },
      {
        id: 'ev_06',
        caseId: 'case_001',
        chapterId: 'ch_02',
        title: 'Estate Gatekeeper Logbook',
        type: 'TIMELINE INFORMATION',
        description: 'Official gate log records Marcus Vance’s black carriage departing at 22:31, not 22:00.',
        detailedNotes: 'The gatekeeper specifically recorded horse lather and rapid reckless departure speed.',
        source: 'Estate Gatehouse Register',
        reliability: 'ABSOLUTE',
        timelineTimestamp: '22:31',
        connectedSuspects: ['Marcus Vance'],
        isDiscovered: false,
        tag: 'TIMELINE',
        boardPosition: { x: 420, y: 350 },
      },
      {
        id: 'ev_07',
        caseId: 'case_001',
        chapterId: 'ch_03',
        title: 'Marcus\'s Sworn Deposition',
        type: 'TESTIMONY',
        description: 'Marcus testifies under official oath: "I kissed Uncle goodnight at 21:50 and departed through the gates at 22:00 sharp."',
        detailedNotes: 'Directly contradicted by Gatekeeper Logbook (ev_06) which records his departure 31 minutes later at 22:31.',
        source: 'Formal Interrogation Room',
        reliability: 'MEDIUM',
        contradictionPairId: 'ev_06',
        connectedSuspects: ['Marcus Vance'],
        isDiscovered: false,
        tag: 'ALIBI CONTRADICTION',
        boardPosition: { x: 700, y: 340 },
      },
      {
        id: 'ev_08',
        caseId: 'case_001',
        chapterId: 'ch_03',
        title: 'Dr. Elena Dispensary Ledger',
        type: 'DOCUMENTS',
        description: 'Medical ledger showing 100mg of potassium cyanide checked out 3 days ago for greenhouse fumigation.',
        detailedNotes: 'Vial was stored in unlocked garden greenhouse cabinet where Marcus was seen earlier.',
        source: 'Doctor Medical Bag',
        reliability: 'HIGH',
        connectedSuspects: ['Dr. Elena Sterling', 'Marcus Vance'],
        isDiscovered: false,
        tag: 'POISON SOURCE',
        boardPosition: { x: 300, y: 540 },
      },
      {
        id: 'ev_09',
        caseId: 'case_001',
        chapterId: 'ch_03',
        title: 'Fountain Pen Reservoir Residue',
        type: 'PHYSICAL EVIDENCE',
        description: 'Gold fountain pen on Arthur\'s desk. The internal bladder was coated with crystallized cyanide salt.',
        detailedNotes: 'Arthur routinely chewed his pen nib while drafting legal codicils. The poison was absorbed through mucous membranes upon pen cap removal.',
        source: 'Victim Mahogany Desk',
        reliability: 'ABSOLUTE',
        connectedSuspects: ['Marcus Vance'],
        isDiscovered: false,
        tag: 'MURDER WEAPON',
        boardPosition: { x: 620, y: 540 },
      },
    ],
    actions: [
      {
        id: 'act_01',
        caseId: 'case_001',
        sceneObjectId: 'obj_desk',
        sceneObjectName: 'Victim Mahogany Desk',
        title: 'SEARCH THE STUDY',
        description: 'Conduct forensic swab of the crystal tumbler and examine ink stains on the desk blotter.',
        costGold: 60,
        reqAttributes: { perception: 3 },
        potentialEvidenceLabel: 'Physical Evidence & Toxicology',
        yieldsEvidenceId: 'ev_01',
        findingsReport: 'Recovered crystal tumbler with trace potassium cyanide clinging to the crystal rim.',
        isExecuted: false,
        locationLabel: 'Study Desk Area',
      },
      {
        id: 'act_08',
        caseId: 'case_001',
        sceneObjectId: 'obj_wastebasket',
        sceneObjectName: 'Study Wastebasket',
        title: 'EXAMINE WASTEBASKET',
        description: 'Inspect the study wastebasket for discarded drafts and torn legal correspondence.',
        costGold: 40,
        reqAttributes: { perception: 2 },
        potentialEvidenceLabel: 'Torn Legal Document',
        yieldsEvidenceId: 'ev_02',
        findingsReport: 'Pieced together Arthur\'s handwritten draft disinheriting Marcus in favor of Clara Giles.',
        isExecuted: false,
        locationLabel: 'Study Corner',
      },
      {
        id: 'act_03',
        caseId: 'case_001',
        sceneObjectId: 'obj_safe',
        sceneObjectName: 'Wall Safe Behind Painting',
        title: 'EXAMINE WALL SAFE',
        description: 'Inspect dial gouge marks and catalog missing bearer bond serials.',
        costGold: 50,
        reqAttributes: { perception: 3 },
        potentialEvidenceLabel: 'Theft Evidence',
        yieldsEvidenceId: 'ev_03',
        findingsReport: 'Found fresh crowbar gouge marks matching forced entry on numbers 4-19-88.',
        isExecuted: false,
        locationLabel: 'North Wall Safe',
      },
      {
        id: 'act_02',
        caseId: 'case_001',
        sceneObjectId: 'obj_laptop',
        sceneObjectName: 'Arthur\'s Laptop Terminal',
        title: 'ANALYZE LAPTOP',
        description: 'Recover deleted file sectors and incoming telegraph cables from the secure disk.',
        costGold: 80,
        reqAttributes: { intelligence: 3 },
        alternateRoute: {
          reqAttributes: { discipline: 3 },
          label: 'Interrogate System Administrator',
        },
        potentialEvidenceLabel: 'Digital Evidence #07',
        yieldsEvidenceId: 'ev_04',
        findingsReport: 'Restored deleted message #07 sent at 22:47 regarding urgent gambling debt.',
        isExecuted: false,
        locationLabel: 'Digital Workstation',
      },
      {
        id: 'act_04',
        caseId: 'case_001',
        sceneObjectId: 'obj_garden',
        sceneObjectName: 'Garden Shed & Flowerbed',
        title: 'SEARCH THE GARDEN',
        description: 'Use flashlight and magnifying lens to search the muddy garden escape route.',
        costGold: 50,
        reqAttributes: { perception: 4 },
        potentialEvidenceLabel: 'Physical Broken Watch',
        yieldsEvidenceId: 'ev_05',
        findingsReport: 'Discovered Marcus Vance\'s crushed gold pocket watch stopped at 22:24.',
        isExecuted: false,
        locationLabel: 'Garden Perimeter',
      },
      {
        id: 'act_05',
        caseId: 'case_001',
        sceneObjectId: 'obj_gate',
        sceneObjectName: 'Gatekeeper Register Log',
        title: 'RECONSTRUCT TIMELINE',
        description: 'Cross-examine gatekeeper records against suspect testimony timelines.',
        costGold: 90,
        reqAttributes: { discipline: 3 },
        alternateRoute: {
          reqAttributes: { intelligence: 3 },
          label: 'Analyze Timestamp Metadata',
        },
        potentialEvidenceLabel: 'Timeline Contradiction',
        yieldsEvidenceId: 'ev_06',
        findingsReport: 'Gatekeeper log confirms Marcus left at 22:31, directly conflicting his 22:00 alibi.',
        isExecuted: false,
        locationLabel: 'Gatehouse Archive',
      },
      {
        id: 'act_06',
        caseId: 'case_001',
        sceneObjectId: 'obj_marcus_interrogate',
        sceneObjectName: 'Interrogation Suite',
        title: 'INTERVIEW MARCUS VANCE',
        description: 'Subject Marcus to aggressive timeline cross-examination regarding his carriage departure.',
        costGold: 70,
        reqAttributes: { discipline: 4 },
        potentialEvidenceLabel: 'Sworn Alibi Testimony',
        yieldsEvidenceId: 'ev_07',
        findingsReport: 'Marcus doubles down on his 22:00 departure alibi, cementing the contradiction with gate logs.',
        isExecuted: false,
        locationLabel: 'Interrogation Suite A',
      },
      {
        id: 'act_09',
        caseId: 'case_001',
        sceneObjectId: 'obj_physician_room',
        sceneObjectName: 'Physician\'s Quarters',
        title: 'INTERVIEW DR. ELENA STERLING',
        description: 'Question Dr. Elena regarding greenhouse pesticide registers and cyanide access logs.',
        costGold: 60,
        reqAttributes: { intelligence: 3 },
        alternateRoute: {
          reqAttributes: { perception: 3 },
          label: 'Search Medical Bag Discreetly',
        },
        potentialEvidenceLabel: 'Toxicology Dispensary Register',
        yieldsEvidenceId: 'ev_08',
        findingsReport: 'Recovered Dr. Elena\'s dispensary ledger showing 100mg potassium cyanide checked out for greenhouse pest control.',
        isExecuted: false,
        locationLabel: 'Doctor\'s Consulting Room',
      },
      {
        id: 'act_07',
        caseId: 'case_001',
        sceneObjectId: 'obj_library',
        sceneObjectName: 'East Library Wing',
        title: 'INSPECT LIBRARY & DESK PEN',
        description: 'Audit Lord Arthur\'s vintage writing desk and inspect his gold fountain pen.',
        costGold: 80,
        reqAttributes: { perception: 4 },
        potentialEvidenceLabel: 'Murder Weapon & Poison Source',
        yieldsEvidenceId: 'ev_09',
        findingsReport: 'Identified cyanide salt coating inside the fountain pen nib chewed by Arthur.',
        isExecuted: false,
        locationLabel: 'East Library Wing',
      },
    ],
    connections: [],
  },
  {
    id: 'case_002',
    code: 'CASE #002',
    title: 'THE SILENT WITNESS',
    subtitle: 'The Vault Breach at Zenith Gallery',
    synopsis:
      'High-security biometric vault compromised during an art gala without triggering infrared alarms. The master sapphire was swapped for a forged glass replica.',
    location: 'Zenith Gallery & High Vault',
    status: 'UNSOLVED',
    currentChapterId: 'ch_02_01',
    reqRank: 'INVESTIGATOR',
    rewardXp: 950,
    rewardGold: 500,
    rewardBadge: 'Silent Witness Seal',
    chapters: [
      {
        id: 'ch_02_01',
        caseId: 'case_002',
        chapterNumber: 1,
        title: 'The Vault Perimeter',
        objective: 'Analyze biometric override logs and inspect ceiling ventilation.',
        isUnlocked: false,
        isCompleted: false,
        requiredEvidenceCount: 3,
      },
    ],
    suspects: [
      {
        id: 'susp_ross',
        name: 'Donald Ross',
        role: 'Gallery Director',
        alibi: 'Hosting VIP donors in the grand salon during the estimated breach time.',
        motiveSummary: 'Mounting private gallery debts to offshore creditors.',
        avatarUrl: '/avatars/ross.png',
        statusNotes: 'Sweating profusely under questioning.',
      },
    ],
    evidence: [],
    actions: [],
    connections: [],
  },
];

export function getServerEvidence(caseId: string, evidenceId: string): EvidenceItem | null {
  const caseDef = SERVER_CASES.find((c) => c.id === caseId);
  if (!caseDef) return null;
  const ev = caseDef.evidence.find((e) => e.id === evidenceId);
  return ev ? { ...ev } : null;
}
